{% set name = "cytoplay" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15ee8668ea1bfeaaddc304d20d8e6d4bebce260c6833b942f38a5c61835350a6
build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.14
    - make 
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - setuptools
    - python
    - pip
    - libblas
    - liblapack
    - pybind11
    - freeglut  # [linux]
    - xorg-libxi
    - xorg-libxmu
    - xorg-libx11  # [linux]
    - glew
    - zlib 
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cytosim2D
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
